// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Build Index of Kitchens
---
*/
package cmds

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path"

	"github.com/magicbutton/365admin-publish/execution"
	"github.com/magicbutton/365admin-publish/schemas"
	"github.com/magicbutton/365admin-publish/utils"
)

func KitchensScanPost(ctx context.Context, args []string) (*schemas.KitchensFound, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "365admin-publish", "docusaurus", "10-scan.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}

	resultingFile := path.Join(utils.WorkDir("365admin-publish"), "kitchens-found.json")
	data, err := os.ReadFile(resultingFile)
	if err != nil {
		return nil, err
	}
	resultObject := schemas.KitchensFound{}
	err = json.Unmarshal(data, &resultObject)
	if utils.Output == "json" {
		fmt.Println(string(data))
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))

	return nil, nil

}
