// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Build Cache files for each Kitchens
---
*/
package cmds

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path"

	"github.com/magicbutton/365admin-publish/execution"
	"github.com/magicbutton/365admin-publish/schemas"
	"github.com/magicbutton/365admin-publish/utils"
)

func KitchensBuildcachePost(ctx context.Context, body []byte, args []string) (*schemas.KitchensBuild, error) {
	inputErr := os.WriteFile(path.Join(utils.WorkDir("365admin-publish"), "kitchens-found.json"), body, 0644)
	if inputErr != nil {
		return nil, inputErr
	}

	result, pwsherr := execution.ExecutePowerShell("john", "*", "365admin-publish", "docusaurus", "20-build.ps1", "")
	if pwsherr != nil {
		return nil, pwsherr
	}

	resultingFile := path.Join(utils.WorkDir("365admin-publish"), "kitchens-build.json")
	data, err := os.ReadFile(resultingFile)
	if err != nil {
		return nil, err
	}
	resultObject := schemas.KitchensBuild{}
	err = json.Unmarshal(data, &resultObject)
	if utils.Output == "json" {
		fmt.Println(string(data))
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))

	return nil, nil

}
