// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Init
---
*/
package cmds

import (
	"context"

	"github.com/magicbutton/365admin-publish/execution"
	"github.com/magicbutton/365admin-publish/utils"
)

func ScaffoldInitwebPost(ctx context.Context, args []string) (*string, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "365admin-publish", "scaffold", "01-initweb.ps1", "", "-kitchenname", GetDirectory(args[0]))
	if pwsherr != nil {
		return nil, pwsherr
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))
	return nil, nil

}
