// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Build Index of Kitchens
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/magicbutton/365admin-publish/execution"
	"github.com/magicbutton/365admin-publish/schemas"
	"github.com/magicbutton/365admin-publish/utils"
)

func KitchensScanPost() usecase.Interactor {
	type Request struct {
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.KitchensFound) error {

		_, err := execution.ExecutePowerShell("john", "*", "365admin-publish", "docusaurus", "10-scan.ps1", "")
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("365admin-publish"), "kitchens-found.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.KitchensFound{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Build Index of Kitchens")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("docusaurus")
	return u
}
